export const REQUEST_MOVIES = 'REQUEST_MOVIES';
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const MOVIE_CREATION_PENDING = 'MOVIE_CREATION_PENDING';
export const MOVIE_CREATION_SUCCESS = 'MOVIE_CREATION_SUCCESS';
export const MOVIE_CREATION_FAILURE = 'MOVIE_CREATION_FAILURE';
