const MOVIES_REQUEST_PENDING = 'MOVIES_REQUEST_PENDING';
const MOVIES_REQUEST_SUCCESS = 'MOVIES_REQUEST_SUCCESS';
const MOVIES_REQUEST_FAILURE = 'MOVIES_REQUEST_FAILURE';
const MOVIE_CREATION_PENDING = 'MOVIE_CREATION_PENDING';
const MOVIE_CREATION_SUCCESS = 'MOVIE_CREATION_SUCCESS';
const MOVIE_CREATION_FAILURE = 'MOVIE_CREATION_FAILURE';
const MOVIE_REQUEST_PENDING = 'MOVIE_REQUEST_PENDING';
const MOVIE_REQUEST_SUCCESS = 'MOVIE_REQUEST_SUCCESS';
const MOVIE_REQUEST_FAILURE = 'MOVIE_REQUEST_FAILURE';
const MOVIE_UPDATE_PENDING = 'MOVIE_UPDATE_PENDING';
const MOVIE_UPDATE_SUCCESS = 'MOVIE_UPDATE_SUCCESS';
const MOVIE_UPDATE_FAILURE = 'MOVIE_UPDATE_FAILURE';
const MOVIE_DELETE_PENDING = 'MOVIE_DELETE_PENDING';
const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
const MOVIE_DELETE_FAILURE = 'MOVIE_DELETE_FAILURE';
const MOVIE_BULK_IMPORT_PENDING = 'MOVIE_BULK_IMPORT_PENDING';
const MOVIE_BULK_IMPORT_SUCCESS = 'MOVIE_BULK_IMPORT_SUCCESS';
const MOVIE_BULK_IMPORT_FAILURE = 'MOVIE_BULK_IMPORT_FAILURE';

export {
  MOVIES_REQUEST_PENDING,
  MOVIES_REQUEST_SUCCESS,
  MOVIES_REQUEST_FAILURE,
  MOVIE_CREATION_PENDING,
  MOVIE_CREATION_SUCCESS,
  MOVIE_CREATION_FAILURE,
  MOVIE_REQUEST_PENDING,
  MOVIE_REQUEST_SUCCESS,
  MOVIE_REQUEST_FAILURE,
  MOVIE_UPDATE_PENDING,
  MOVIE_UPDATE_SUCCESS,
  MOVIE_UPDATE_FAILURE,
  MOVIE_DELETE_PENDING,
  MOVIE_DELETE_SUCCESS,
  MOVIE_DELETE_FAILURE,
  MOVIE_BULK_IMPORT_PENDING,
  MOVIE_BULK_IMPORT_SUCCESS,
  MOVIE_BULK_IMPORT_FAILURE
}
