const FETCH_FORMAT_LIST_PENDING = "FETCH_FORMAT_LIST_PENDING";
const FETCH_FORMAT_LIST_SUCCESS = "FETCH_FORMAT_LIST_SUCCESS";
const FETCH_FORMAT_LIST_FAILURE = "FETCH_FORMAT_LIST_FAILURE";

export {
  FETCH_FORMAT_LIST_PENDING,
  FETCH_FORMAT_LIST_SUCCESS,
  FETCH_FORMAT_LIST_FAILURE
};
