export const SIGN_IN_FINISH_REQUEST_PENDING = "SIGN_IN_FINISH_REQUEST_PENDING";
export const SIGN_IN_FINISH_REQUEST_FAILURE = "SIGN_IN_FINISH_REQUEST_FAILURE";
export const SIGN_IN_FINISH_REQUEST_SUCCESS = "SIGN_IN_FINISH_REQUEST_SUCCESS";
