export const FACEBOOK_LOGIN_REQUEST_PENDING = 'FACEBOOK_LOGIN_REQUEST_PENDING';
export const FACEBOOK_LOGIN_REQUEST_SUCCESS = 'FACEBOOK_LOGIN_REQUEST_SUCCESS';
export const FACEBOOK_LOGIN_REQUEST_FAILURE = 'FACEBOOK_LOGIN_REQUEST_FAILURE';
